### ISSUE TITLE
%c in JS Console window

### ISSUE THREAD

**Issue by cpottamus** [thegroundwork/groundwork.js#10]
Really love the introductory console message from the groundwork.js Utils!

Seeing some slight formatting issues, with a few stray "%c" being printed out to console.

![screen shot 2016-06-29 at 9 52 19 am](https://cloud.githubusercontent.com/assets/2238143/16456925/50ba7ee4-3ddf-11e6-92ce-39bc03611c76.png)

**Comment by DarrenN** [comment]
I don't even know what you're referring too. Where do you see this console text?

**Comment by cpottamus** [comment]
Sorry, sort of just tossed that over the wall.

Logged into the dev version of [payments block](https://developer.dev.thegroundwork.com/tools/blocks/payments/) and viewed the console in Chrome. 

I see a print out in the console welcoming me to Groundwork.js and explaining some basic functionality, it's being pulled from utils.js

![screen shot 2016-06-29 at 10 09 41 am](https://cloud.githubusercontent.com/assets/2238143/16457655/d676518c-3de1-11e6-8f6e-6f15d4444ee1.png)

**Comment by DarrenN** [comment]
Wrong repo: https://github.com/thegroundwork/developer-center/blob/0efa332e79298c0a458dc3f01091be63235150b4/src/js/src/greeter.js
