### ISSUE TITLE
Unfreeze schema objects

### ISSUE THREAD

**Issue by DarrenN** [thegroundwork/groundwork.js#33]
There are rare cases in which `tv4` attempts to modify the `id` of a JSON Schema. Since we froze those, this throws an error and stops the whole show. When I dug into the compiled modules (Supporters in this case) and removed the `freeze` around the schema all was well.

**Comment by damassi** [comment]
@DarrenN - Any clue why tv4 is modifying the ID? Is this at runtime?

**Comment by DarrenN** [comment]
@damassi Hi yes, this was at runtime. When doing validation, at certain points it was mutating the `id` field. As to _why_ I have no idea why it felt like it needed to do that, and in fact it could be an accident. JS makes those kinds of accidents real easy.
