### ISSUE TITLE
Compiled common.js contains ES6 statements such as `let`

### ISSUE THREAD

**Issue by DarrenN** [thegroundwork/groundwork.js#34]
When using the modular build for Timshel.com I got a bunch of errors during the Uglification step because common.js had ES6 statements (`let` - line 8071). I had to manually tell webpack to parse the `groundwork.js` node module to alleviate the issue. This allowed me to get the module compiled in, but still gave Uglify fits because now it was being told to uglify already minified code.

We need to make sure `common.js` is compiled down to ES5

**Comment by damassi** [comment]
On it ☝️
